name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
concurrency:
  group: publish
  cancel-in-progress: true
permissions: write-all
jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - uses: actions/configure-pages@v3
      - run: npm run build:docs
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist
      - id: deploy-pages
        uses: actions/deploy-pages@v2
